name: Build Flatpak
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:latest
      options: --privileged
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: nz.mega.MEGAsync.yml
          bundle: megasync.flatpak
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: true
